---
abstract: 'Simple file-viewing widget for Tickit'
author:
  - 'Tom Molesworth <cpan@perlsite.co.uk>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::CheckDeps: '0.010'
  Test::More: '0.98'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.031, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Tickit-Widget-FileViewer
no_index:
  directory:
    - eg
    - share
    - shares
    - t
    - xt
provides:
  Tickit::Widget::FileViewer:
    file: lib/Tickit/Widget/FileViewer.pm
    version: '0.005'
requires:
  Text::Tabs: '0'
  Tickit: '0.74'
  Tickit::Widget: '0.58'
  parent: '0'
resources:
  bugtracker: https://github.com/team-at-cpan/Tickit-Widget-FileViewer/issues
  homepage: https://github.com/team-at-cpan/Tickit-Widget-FileViewer
  repository: https://github.com/team-at-cpan/Tickit-Widget-FileViewer.git
version: '0.005'
x_authority: cpan:TEAM
x_contributors:
  - 'Tom Molesworth <tom@perlsite.co.uk>'
  - 'Tom Molesworth <TEAM@cpan.org>'
x_generated_by_perl: v5.38.0
x_serialization_backend: 'YAML::Tiny version 1.74'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
